"""Implementing course_id in enrollment and courseinstructor

Revision ID: 3b42b3342d11
Revises: 74ec682fbbf7
Create Date: 2023-11-17 11:26:16.234694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b42b3342d11'
down_revision = '74ec682fbbf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course instructors', sa.Column('course_id', sa.String(), nullable=False))
    op.add_column('course instructors', sa.Column('session', sa.String(), nullable=False))
    op.drop_constraint('course instructors_course_code_fkey', 'course instructors', type_='foreignkey')
    op.create_foreign_key(None, 'course instructors', 'courses', ['course_id'], ['course_id'], ondelete='CASCADE')
    op.add_column('enrollments', sa.Column('course_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'course_code')
    op.drop_constraint(None, 'course instructors', type_='foreignkey')
    op.create_foreign_key('course instructors_course_code_fkey', 'course instructors', 'courses', ['course_code'], ['course_code'], ondelete='CASCADE')
    op.drop_column('course instructors', 'session')
    op.drop_column('course instructors', 'course_id')
    # ### end Alembic commands ###
