"""Add title to Student table

Revision ID: 4f57a06c1d91
Revises: 7c61825cd62c
Create Date: 2023-11-07 13:07:40.328272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f57a06c1d91'
down_revision = '7c61825cd62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'title')
    # ### end Alembic commands ###
