"""Add title to instructor table

Revision ID: 7c61825cd62c
Revises: 07c8d8b13f4d
Create Date: 2023-11-07 10:54:58.722514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c61825cd62c'
down_revision = '07c8d8b13f4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'title')
    # ### end Alembic commands ###
