"""Add is_completed column to assessment table

Revision ID: 9c29045ad77d
Revises: e458696e0071
Create Date: 2023-12-04 10:39:54.311891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c29045ad77d'
down_revision = 'e458696e0071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('is_completed', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'is_completed')
    # ### end Alembic commands ###
