"""Add student level to student table

Revision ID: e458696e0071
Revises: 4f57a06c1d91
Create Date: 2023-11-16 18:13:18.346219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e458696e0071'
down_revision = '4f57a06c1d91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('level', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'level')
    # ### end Alembic commands ###
