wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.4
    framework: lightgbm
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687755376.279704
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 8
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 23
      4: 3.10.10
      5: 0.15.4
      6: 4.30.2
      8:
      - 3
      - 5
      - 9
